import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'motion/react';
import { ChevronRight, CheckCircle2, BookOpen, Clock, Award, Languages } from 'lucide-react';
import { useLanguageStore, useModuleStore } from '../store/globalStore';
import { generateModuleContentStream, translateModuleContent } from '../services/geminiService';
import { VoicePlayback } from '../components/VoicePlayback';
import { AIChatDrawer } from '../components/AIChatDrawer';
import { NotesPanel } from '../components/NotesPanel';

export const ModuleLearningPage = () => {
  const { id } = useParams();
  const { language, setLanguage } = useLanguageStore();
  const { completedModules, modules, isModuleUnlocked } = useModuleStore();
  const navigate = useNavigate();
  
  const module = modules.find(m => m.id === id);
  const [content, setContent] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  const [streamProgress, setStreamProgress] = useState(0);
  const [isChatOpen, setIsChatOpen] = useState(false);

  useEffect(() => {
    if (!isModuleUnlocked(id || '')) {
      navigate('/student/modules');
      return;
    }

    const fetchContent = async () => {
      setLoading(true);
      setContent(null); 
      
      // 1. Normalize content structure
      let contentMap: { [lang: string]: any } = {};
      if (module?.content) {
        if (module.content.sections && !module.content.en) {
          contentMap = { en: module.content };
        } else {
          contentMap = module.content;
        }
      }

      // 2. Check if we already have this language
      if (contentMap[language]) {
        console.log(`[ModuleLearningPage] Content found in module for language: ${language}`);
        setContent(contentMap[language]);
        setLoading(false);
        return;
      }

      // 3. Check Cache
      const cacheKey = `module_cache_${id}_${language}`;
      const cachedData = localStorage.getItem(cacheKey);
      if (cachedData) {
        console.log(`[ModuleLearningPage] Cache hit for language: ${language}`);
        setContent(JSON.parse(cachedData));
        setLoading(false);
        return;
      }

      // 4. Translation Logic (If not English)
      if (language !== 'en') {
        try {
          const sourceContent = contentMap['en'];
          if (sourceContent) {
            console.log(`[ModuleLearningPage] Triggering translation from en to ${language}`);
            const translated = await translateModuleContent(sourceContent, language);
            if (translated) {
              localStorage.setItem(cacheKey, JSON.stringify(translated));
              setContent(translated);
              setLoading(false);
              return;
            }
          }
        } catch (error) {
          console.error("Translation failed", error);
        }
      }

      // 5. Generation Logic (If translation failed or English is missing)
      try {
        const generated = await generateModuleContentStream(
          module?.title || `Module ${id}`,
          language,
          module?.headings,
          (text) => {
            const progress = Math.min(Math.round((text.length / 3000) * 100), 99);
            setStreamProgress(progress);
          }
        );
        if (generated) {
          setContent(generated);
        }
      } catch (error) {
        console.error("Generation failed", error);
      } finally {
        setLoading(false);
      }
    };

    fetchContent();
  }, [id, language, modules]);

  const handleLanguageChange = (lang: string) => {
    setLanguage(lang);
  };

  if (!content && !loading) {
    return (
      <div className="flex flex-col items-center justify-center h-[60vh] gap-4">
        <div className="w-20 h-20 bg-white/5 rounded-3xl flex items-center justify-center text-white/20 border border-white/10">
          <BookOpen size={40} />
        </div>
        <div className="text-center">
          <h2 className="text-xl font-bold text-white">Content Not Available</h2>
          <p className="text-white/40 text-sm max-w-xs mx-auto mt-2">
            This module's content hasn't been generated by the administrator yet.
          </p>
        </div>
        <button 
          onClick={() => navigate('/student/dashboard')}
          className="mt-4 px-6 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-sm font-medium transition-all"
        >
          Back to Dashboard
        </button>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-[80vh] gap-6">
        <div className="relative">
          <div className="w-24 h-24 border-4 border-indigo-500/10 border-t-indigo-500 rounded-full animate-spin" />
          <div className="absolute inset-0 flex items-center justify-center">
            <BookOpen size={32} className="text-indigo-500" />
          </div>
        </div>
        <div className="text-center space-y-2">
          <h2 className="text-xl font-bold text-white">
            {language === 'en' ? 'Loading Module' : 'Translating content...'}
          </h2>
          <p className="text-white/40 text-sm">
            {language === 'en' ? 'Preparing your lesson...' : `Crafting lesson in ${language}...`}
          </p>
        </div>
        {language !== 'en' && streamProgress > 0 && (
          <div className="w-64 h-2 bg-white/5 rounded-full overflow-hidden border border-white/10">
            <motion.div 
              initial={{ width: 0 }}
              animate={{ width: `${streamProgress}%` }}
              className="h-full bg-indigo-500 shadow-[0_0_15px_rgba(99,102,241,0.5)]"
            />
          </div>
        )}
      </div>
    );
  }

  return (
    <div className="max-w-7xl mx-auto">
      {/* Top Bar */}
      <div className="flex items-center justify-between mb-8 bg-white/5 backdrop-blur-xl border border-white/10 p-4 rounded-2xl sticky top-4 z-40">
        <div className="flex items-center gap-4">
          <div className="w-10 h-10 bg-indigo-600 rounded-xl flex items-center justify-center">
            <BookOpen size={20} />
          </div>
          <div>
            <h1 className="font-bold text-lg">{content?.module_title || content?.title || `Module ${id}`}</h1>
            <div className="flex items-center gap-4 text-xs text-white/40">
              <span className="flex items-center gap-1"><Clock size={12} /> 45 mins</span>
              <span className="flex items-center gap-1"><Award size={12} /> 100 XP</span>
            </div>
          </div>
        </div>

        <div className="flex items-center gap-4">
          <VoicePlayback 
            text={
              Array.isArray(content?.sections) 
                ? content.sections.map((s: any) => `${s.heading}. ${s.content}. ${s.key_points?.join('. ') || ''}. ${s.example || ''}`).join(' ')
                : (content?.objectives_summary || content?.summary || '')
            } 
            language={language} 
          />
          
          <div className="flex items-center gap-2 bg-white/5 rounded-full px-4 py-2 border border-white/10 hover:bg-white/10 transition-colors">
            <Languages size={16} className="text-indigo-400" />
            <select
              value={language}
              onChange={(e) => handleLanguageChange(e.target.value)}
              className="bg-transparent text-sm border-none focus:ring-0 cursor-pointer font-medium text-white/80 appearance-none pr-2"
            >
              <option value="en" className="bg-[#1a1a1a] text-white">English</option>
              <option value="ta" className="bg-[#1a1a1a] text-white">Tamil</option>
            </select>
          </div>

          <button
            onClick={() => navigate(`/student/quiz/${id}`)}
            className="bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 px-6 py-2 rounded-xl font-semibold text-sm transition-all shadow-lg shadow-indigo-500/20"
          >
            Ready for Quiz
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left: Content */}
        <div className="lg:col-span-2 space-y-8">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="bg-white/5 border border-white/10 rounded-3xl p-8"
          >
            <h2 className="text-xl font-bold mb-6 flex items-center gap-2">
              <CheckCircle2 className="text-emerald-400" size={20} />
              Learning Objectives
            </h2>
            <div className="text-white/70 text-sm leading-relaxed bg-white/5 p-6 rounded-2xl border border-white/5">
              {content?.objectives_summary || content?.learningObjectives?.join('. ')}
            </div>
          </motion.div>

          {content?.sections?.map((section: any, i: number) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.1 }}
              className="bg-white/5 border border-white/10 rounded-3xl p-8 space-y-6"
            >
              <h3 className="text-2xl font-bold text-indigo-400">{section.heading}</h3>
              <div className="prose prose-invert max-w-none text-white/80 leading-relaxed">
                {section.content}
              </div>
              
              {section.key_points && section.key_points.length > 0 && (
                <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                  {section.key_points.map((point: string, idx: number) => (
                    <div key={idx} className="flex items-center gap-3 bg-white/5 p-3 rounded-xl border border-white/5 text-xs text-white/60">
                      <div className="w-1.5 h-1.5 rounded-full bg-indigo-500 shrink-0" />
                      {point}
                    </div>
                  ))}
                </div>
              )}

              {section.example && (
                <div className="bg-indigo-600/5 rounded-2xl p-6 border border-indigo-500/10">
                  <span className="text-[10px] text-indigo-400 uppercase tracking-widest font-black block mb-2">Example</span>
                  <p className="text-white/70 text-sm italic leading-relaxed">{section.example}</p>
                </div>
              )}

              {section.code && (
                <div className="mt-6 bg-black/50 rounded-2xl p-6 font-mono text-sm border border-white/5 overflow-x-auto">
                  <pre className="text-indigo-300">
                    <code>{section.code}</code>
                  </pre>
                </div>
              )}
            </motion.div>
          ))}

          {/* Summary Section */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            className="bg-indigo-600/10 border border-indigo-500/20 rounded-3xl p-8"
          >
            <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
              <Award className="text-indigo-400" size={20} />
              Summary
            </h2>
            <p className="text-white/70 italic leading-relaxed">
              {content?.objectives_summary || content?.summary || "You have successfully completed this module's lessons. Review the key points above before taking the quiz."}
            </p>
          </motion.div>
        </div>

        {/* Right: Notes Editor */}
        <div className="lg:col-span-1">
          <div className="sticky top-28 space-y-6">
            <NotesPanel moduleId={id || ''} />

            <div className="bg-gradient-to-br from-indigo-600/20 to-purple-600/20 border border-white/10 rounded-3xl p-6">
              <h4 className="font-bold text-sm mb-2">Need help?</h4>
              <p className="text-xs text-white/60 mb-4">Ask our AI assistant about this module's content.</p>
              <button 
                onClick={() => setIsChatOpen(true)}
                className="w-full py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-xs font-semibold transition-all"
              >
                Open AI Chat
              </button>
            </div>
          </div>
        </div>
      </div>

      <AIChatDrawer 
        isOpen={isChatOpen}
        onClose={() => setIsChatOpen(false)}
        moduleTitle={module?.title || ''}
        moduleContent={JSON.stringify(content)}
      />
    </div>
  );
};
